### ISSUE TITLE
How to turn off headers 

### ISSUE THREAD

**Issue by klaw1** [meitar/inline-gdocs-viewer#24]
I am able to select the data, but it shows more than I needed, how can I turn off the displaying of headers such as "[Column] [visibility] [Copy] [CSV] [Excel] [PDF] [Print]  [Show] 102550100 entries Search:, etc and only show my cell?

Thanks,
K

**Comment by meitar** [comment]
Please use the plugin support forum for support questions; your question has been [answered there](https://wordpress.org/support/topic/disable-buttons-2/) many, [*many* times](https://wordpress.org/support/topic/disable-buttons/). This space is for bug reports, feature requests, and other development tasks.

**Comment by klaw1** [comment]
Thanks.  Sorry, I thought I looked and didn't see it.  But how about the
others like Show 10 entires and Search: box?

-- 
ESG Manager
380 Cory Hall, U. C. Berkeley
(510) 643-0843
