### ISSUE TITLE
Formatting two or more columns together?

### ISSUE THREAD

**Issue by mmazanec22** [meitar/inline-gdocs-viewer#25]
Hello!  I was very excited to discover this plugin and can't wait to see what my org does with it.  An example of the type of thing I'm hoping to do is turn long, difficult to maintain lists like this [list of city projects](https://beta.ashevillenc.gov/department/communication-public-engagement/projects-and-initiatives/) and [this (inaccessible!) one for meeting minutes](https://beta.ashevillenc.gov/government/city-council-meeting-materials/) into nice tables.

So far [I've got a table](https://sheets-test-avlbeta.pantheonsite.io/department/communication-public-engagement/projects-and-initiatives/), but can't figure out how to format columns quite the way I want.  I'd like to be able to take a few columns-- say date, label, and link-- and make them into one column that is something like `<a href="the link">{date} {label}</a>`.

It seemed like the query API could work but even the most basic query I tried returned an error.

What's the best way to go about this?  Do you have any examples for a query?

**Comment by meitar** [comment]
I would use the `gdoc_table_html` filter for this because, IIUC, you still want your individual fields as discrete objects returned from the query, you just want to display them in a merged cell on the front end.
