### ISSUE TITLE
WordPress throws error when trying a page with a gdoc query shortcode

### ISSUE THREAD

**Issue by martijn19811** [meitar/inline-gdocs-viewer#27]
Hi,

first of all, I'll quickly state my specs. My site is running on:

- PHP 7.2.29 (Apache)
- WordPress 5.3.2
- the following plugins: Contact Form 7, Events Made Easy, NextGEN gallery, ShortPixel image optimizer, W3 Total Cache, WP-Optimize and Yoast SEO.. and Inline Google Spreadsheet viewer of course. Version 0.13.1

I am an administrator of the website and I've enabled the possibility to SQL query in the settings. However, when I want to insert the [gdoc] shortcode in a normal page, things go awry.

- All goes well when only using [gdoc] shortcode itself
- The moment I want to query with either `[gdoc key="wordpress"]` or `[gdoc key="mysql"]` and I want to save the page, a red alert appears, saying: '_The response is not a valid JSON response_'. 

Checking the POST call WordPress makes when clicking the save button and it returns the following error:
`<h1>Error thrown</h1><p>Call to a member function has_cap() on boolean</p>`

**Comment by martijn19811** [comment]
It seems it's Yoast SEO fault. When disabling that plugin, the error completely disappears.

**Comment by meitar** [comment]
> Oddly enough, things do seem to go well when disabling the Yoast SEO plugin. I am not sure which plugin is to 'blame'.

One day, a patient came to their doctor and said, "Doctor, it hurts when I do this."

"Hmm," the doctor said. "Well, don't do that."

**Comment by martijn19811** [comment]
I've been a developer for quite some years now. I've submitted a few issues to different kind of repositories. The feedback I received was always great. People showing interest in how their plugin can actually be improved.

That's why I'm baffled by the response above. Not only does this metaphor feels very condescending, but basically stating: "well, if it doesn't work with **this** plugin, simply stop using it", feels like a complete lack of interest.

If you've looked through the stacktrace and quickly decided that this is not the fault of the inline gdocs viewer, then great. Please state so in a clear manner and we're all good :). Then I do know I should bother other people.

I'm a fan of your work itself. The viewer is pretty good. But please understand this is just an honest attempt to sort out bugs and get them fixed, in order to improve the plugin. I've clearly stated the problem, I've even added a stacktrace and thereby I hope I've showed you enough respect. All I ask is the same from your side.

**Comment by meitar** [comment]
This issue seems to be [the same issue as this one posted on the Support forum I no longer monitor](https://wordpress.org/support/topic/gdoc-query-shortcode-causes-invalid-json-response-error-when-saving/). This posting was made exactly one day after that original one.

You're trying to get me to support a plugin that I *explicitly* and *vocally* no longer support. I don't feel like that's showing me any respect, and therefore I don't feel like I owe you any, either.

If you want the bug fixed, send me a patch. Otherwise, don't waste any more of my time.

**Comment by martijn19811** [comment]
Wow. Alright, if you really feel this way: consider transferring the ownership of this repository to someone else. By not supporting this plugin in any way possible, you're not making things easier for people actively using this tool. I'm sure we can agree on that, right? :)

Again, despite what you're saying to me, I **am** a fan of your work and I do not think this work should go to waste this way. If we, as the WordPress community, can keep this plugin alive and kicking by handing this repository to someone else, then we should consider that.

**Comment by meitar** [comment]
As the readme of this plugin clearly describes, it is the "WordPress community" that made me so fucking bitter about spending my time trying to support this plugin for them in the first place. ¯\_(ツ)_/¯ Fork at will.

**Comment by martijn19811** [comment]
No, I will not do that. It's clear to me that this plugin cannot receive the attention it should have. Without anyone else being able to take care of this repository, I should know better and look elsewhere. Thanks for your time.

**Comment by meitar** [comment]
All right then. Good luck.
