### ISSUE TITLE
Update all DataTables dependencies to its latest versions

### ISSUE THREAD

**Issue by martijn19811** [meitar/inline-gdocs-viewer#28]
I'm having a lot of trouble with the responsiveness of the generated tables as setup by Inline Gdocs Viewer. A quick look in the source code revealed that the DataTables plugin files haven't been updated in nearly 3 years! Please see [for yourself](https://cdn.datatables.net/)

Please update all files, so that the dataTables plugin will behave better.

**Comment by meitar** [comment]
> A quick look in the source code revealed that the DataTables plugin files haven't been updated in nearly 3 years!

You say this as though this is a travesty, but [there have only been two patch releases between then and now](https://cdn.datatables.net/releases.html). That said, updating is simple and so if I don't immediately detect any issues, I will go ahead and do that when I have some spare time.

**Comment by meitar** [comment]
Version 0.13.2 updates all included libraries to their latest versions.

For what it's worth, you could also have used the `gdoc_enqueued_front_end_*` filters to do this yourself.
